version: 2
executorType: machine
stages:
  build:
    workDir: ~/imagemagick-deb
    steps:
      - type: checkout
      - type: shell
        name: Build image
        command: |
          cd trusty
          docker-compose build
          docker-compose run imagemagick
      - type: shell
        name: Show tree
        command: apt-get install -y tree && tree
      - type: shell
        name: Upload package
        command: aws s3 cp ~/imagemagick-deb/trusty/out/imagemagick_6.9.7-10-trusty-talis_amd64.deb s3://aspire-operations/binaries/aptly/imagemagick_6.9.7-10-trusty-talis_amd64.deb
